name 'libtool'
maintainer 'Martin Melik Merkumians'
maintainer_email 'melik-merkumians@acin.tuwien.ac.at'
license 'MIT'
description 'Installs/Configures libtool'
long_description 'Installs/Configures libtool'
version '0.1.0'
